config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :restaurants do
    resources :reviews, only: [:index, :new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CUISINES = ['chinese', 'italian', "japanese", "french", "belgian"]
  validates :name, presence: true, uniqueness: true
  validates :address, presence: true, uniqueness: true
  validates :category, inclusion: { in: CUISINES }

  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  RATING = [0, 1, 2, 3, 4, 5]
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: RATING }

  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save

    redirect_to restaurant_path(@restaurant)
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    # No need for app/views/restaurants/destroy.html.erb
    redirect_to restaurants_path, status: :see_other
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create index]

def index
  @reviews = @restaurant.reviews
end

def new
  # We need @restaurant in our `simple_form_for`
  @review = Review.new
end

def create
  @review = Review.new(review_params)
  @review.restaurant = @restaurant
  if @review.save
    redirect_to restaurant_path(@restaurant)
  else
    render :new, status: :unprocessable_entity
  end

end

private

def set_restaurant
  @restaurant = Restaurant.find(params[:restaurant_id])
end

def review_params
  params.require(:review).permit(:content, :rating)
end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<div class="container">
<h1>Edit Restaurant</h1>

  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.select :category, Restaurant::CUISINES %>
    <%= f.submit %>
  <% end %>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>Restaurants</h1>
    <div class="row">
      <% @restaurants.each do | restaurant | %>
        <ul>
          <li>
            <%= link_to restaurant.name, restaurant_path(restaurant) %>
          </li>
        </ul>
      <% end %>
    </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
<h1>Add New Restaurant</h1>

  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.select :category, Restaurant::CUISINES %>
    <%= f.submit %>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
<h1>Show Restaurant Details</h1>
<ul>
  <li>Name: <%= @restaurant.name %></li>
  <li>Address: <%= @restaurant.address %></li>
  <li>Phone: <%= @restaurant.phone_number %></li>
  <li>Cuisine: <%= @restaurant.category %></li>
  <%= link_to "Back to list", restaurants_path %>
  <%= link_to "See reviews", restaurant_reviews_path(@restaurant) %>
  <%= link_to "Add new reviews", new_restaurant_review_path(@restaurant) %>
</ul>

<%# <%= link_to "Delete",
  restaurant_path(@restaurant),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>


</div>

app/views/reviews/index.html.erb
<div class="container">
  <h1>Reviews</h1>
    <div class="row">
      <% @reviews.each do | review | %>
        <ul>
          <li>
            <%= review.content %>
          </li>
        </ul>

      <% end %>
       <%= link_to "Back to list", restaurants_path %>
        <%= link_to "Add a review", new_restaurant_review_path(@restaurant) %>
    </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
<h1>New review submission</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <h3>Add a review for "<%= @restaurant.name %>"</h3>
  <p> Your comments: <%= f.input :content %></p>
  <p> How many stars: <%= f.input :rating %> </p>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>
  <%= link_to "Back to list", restaurants_path %>
  <%= link_to "See reviews", restaurant_reviews_path(@restaurant) %>
</div>